### ISSUE TITLE
Bug with February

### ISSUE THREAD

**Issue by florentsorel** [carvefx/calendar#6]
Hi,

There is a bug with the February month, the last week is missing.

![image](https://cloud.githubusercontent.com/assets/1011503/24918846/1a3ea69e-1ee2-11e7-963a-814bdd4c7185.png)

I display the calendar with the code in the docs.

**Comment by mikemand** [comment]
Hi @florentsorel,

The tagged version (`0.1` as of right now) does not contain the fix for this problem. You'll need to use `dev-master` or `*` as your version in `composer.json`.

**Comment by florentsorel** [comment]
Indeed ;)

Thank you.
